### ISSUE TITLE
graphcast missing in dataset

### ISSUE THREAD

**Issue by akhtarvision** [google-research/weatherbench2#110]
Hi. Thanks for the great initiative

I see the Graphcast dataset folder is missing in the bucket "weatherbench2/datasets"? @shoyer @raspstephan

**Comment by raspstephan** [comment]
Hey, we currently don't have GraphCast forecasts o the public cloud bucket. Hopefully this will change soon.

**Comment by akhtarvision** [comment]
Okay, thanks for the information. I tried to get predictions from graphcast model but it seems that there are some key mismatches, that I have been trying to resolve. If you have any resource that makes the exact format the weather bench requires, do let me know. Thanks

**Comment by raspstephan** [comment]
Could you be more specific about those mismatches? Maybe I can help then.

**Comment by akhtarvision** [comment]
Can you give some pointers for getting predictions from Graphcast or any other weather prediction model and converting them into the exact format required for weatherbenchv2? A quick reply will be great. @raspstephan

**Comment by raspstephan** [comment]
Can you share what the dataset looks like and what command you ran that gave you the error?

**Comment by akhtarvision** [comment]
![image](https://github.com/google-research/weatherbench2/assets/50232106/b06f55e3-a4b7-401c-82ec-cf5c540d9274)

And this command gives error: "evaluate_in_memory(data_config, eval_configs)   # Takes around 5 minutes"

**Comment by raspstephan** [comment]
Hey, your forecast is missing a dimension. The dataset only has a timedelta but it doesn't actually specify when the forecast was initialized. Check the datasets here https://weatherbench2.readthedocs.io/en/latest/data-guide.html to see what the standard format for forecast files it. 

Regarding out of memory: Depending on how much RAM you have, evaluation can be hard to do in memory. In this case, you probably want to look at  distributed evaluation: https://weatherbench2.readthedocs.io/en/latest/beam-in-the-cloud.html or choose a smaller time slice.
