### ISSUE TITLE
Support calculation of metrics (s.a. RMSE) for each grid point

### ISSUE THREAD

**Issue by LevanBokeria** [google-research/weatherbench2#123]
Does weatherbench2 currently support calculating RMSE (or other metrics) scores at each point on the grid, as opposed to outputting the weighted averages? 

This would be very useful when using WB2 for model development where its important to check where on the globe a model is doing well vs poorly.

**Comment by raspstephan** [comment]
Yes, you can use the spatial metrics, e.g. https://weatherbench2.readthedocs.io/en/latest/_autosummary/weatherbench2.metrics.SpatialMSE.html#weatherbench2.metrics.SpatialMSE
