### ISSUE TITLE
Incorrect paths for Keisler

### ISSUE THREAD

**Issue by hyunju-jung** [google-research/weatherbench2#136]
I have just noticed that paths for output of Keisler (2022) are incorrect. Files on the [Data Guide page](https://weatherbench2.readthedocs.io/en/latest/data-guide.html#keisler-2022) for Keisler should be changed from

`2020-240x121_equiangular_with_poles_conservative_mean.zarr` 
`2020-64x32_equiangular_conservative_mean.zarr`

to

`2020-240x121_equiangular_with_poles_conservative.zarr` 
`2020-64x32_equiangular_conservative.zarr`

**Comment by shoyer** [comment]
@hyunju-jung thanks for pointing this out!
