### ISSUE TITLE
it seems the climatology file in the  evaluation.ipynb quick setup guide seems to be missing

### ISSUE THREAD

**Issue by ShileiCao** [google-research/weatherbench2#214]
FileNotFoundError: No such file or directory: 'gs://weatherbench2/datasets/era5-hourly-climatology/1990-2019_6h_64x32_equiangular_conservative.zarr'

**Comment by ShileiCao** [comment]
when i replace it with “with_poles”, the file can be read. But it went wrone when I run the evaluation：

evaluate_in_memory(data_config, eval_configs)

/usr/local/lib/python3.10/dist-packages/weatherbench2/evaluation.py:67: FutureWarning: The return type of `Dataset.dims` will be changed to return a set of dimension names in future, in order to be more consistent with `DataArray.dims`. To access a mapping from dimension names to lengths, please use `Dataset.sizes`.
  if not min(dataset.dims.values()):
/usr/local/lib/python3.10/dist-packages/weatherbench2/evaluation.py:67: FutureWarning: The return type of `Dataset.dims` will be changed to return a set of dimension names in future, in order to be more consistent with `DataArray.dims`. To access a mapping from dimension names to lengths, please use `Dataset.sizes`.
  if not min(dataset.dims.values()):
/usr/local/lib/python3.10/dist-packages/weatherbench2/evaluation.py:67: FutureWarning: The return type of `Dataset.dims` will be changed to return a set of dimension names in future, in order to be more consistent with `DataArray.dims`. To access a mapping from dimension names to lengths, please use `Dataset.sizes`.
  if not min(dataset.dims.values()):
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-69-949b6aea146d>](https://localhost:8080/#) in <cell line: 1>()
----> 1 evaluate_in_memory(data_config, eval_configs)   # Takes around 5 minutes

9 frames
[/usr/local/lib/python3.10/dist-packages/weatherbench2/evaluation.py](https://localhost:8080/#) in evaluate_in_memory(data_config, eval_configs, skipna)
    515   """
    516   for eval_name, eval_config in eval_configs.items():
--> 517     _evaluate_all_metrics(eval_name, eval_config, data_config, skipna=skipna)
    518 
    519 

[/usr/local/lib/python3.10/dist-packages/weatherbench2/evaluation.py](https://localhost:8080/#) in _evaluate_all_metrics(eval_name, eval_config, data_config, skipna)
    475     truth = truth.sel(time=forecast.valid_time)
    476 
--> 477   results = _metric_and_region_loop(forecast, truth, eval_config, skipna=skipna)
    478 
    479   logging.info(f'Logging Evaluation complete:\n{results}')

[/usr/local/lib/python3.10/dist-packages/weatherbench2/evaluation.py](https://localhost:8080/#) in _metric_and_region_loop(forecast, truth, eval_config, skipna, compute_chunk)
    421             [region_name], coords={'region': [region_name]}
    422         )
--> 423         tmp_result = eval_fn(
    424             forecast=forecast, truth=truth, region=region, skipna=skipna
    425         )

[/usr/local/lib/python3.10/dist-packages/weatherbench2/metrics.py](https://localhost:8080/#) in compute(self, forecast, truth, region, skipna)
    131           f"Forecast has neither valid_time or init_time dimension {forecast}"
    132       )
--> 133     return self.compute_chunk(
    134         forecast, truth, region=region, skipna=skipna
    135     ).mean(

[/usr/local/lib/python3.10/dist-packages/weatherbench2/metrics.py](https://localhost:8080/#) in compute_chunk(self, forecast, truth, region, skipna)
    405     forecast_anom = forecast - climatology_chunk
    406     truth_anom = truth - climatology_chunk
--> 407     return _spatial_average(
    408         forecast_anom * truth_anom,
    409         region=region,

[/usr/local/lib/python3.10/dist-packages/weatherbench2/metrics.py](https://localhost:8080/#) in _spatial_average(dataset, region, skipna)
    154     dataset: Spatially averaged metric.
    155   """
--> 156   weights = get_lat_weights(dataset)
    157   if region is not None:
    158     dataset, weights = region.apply(dataset, weights)

[/usr/local/lib/python3.10/dist-packages/weatherbench2/metrics.py](https://localhost:8080/#) in get_lat_weights(ds)
     57   weights = _cell_area_from_latitude(np.deg2rad(ds.latitude.data))
     58   weights /= np.mean(weights)
---> 59   weights = ds.latitude.copy(data=weights)
     60   return weights
     61 

[/usr/local/lib/python3.10/dist-packages/xarray/core/dataarray.py](https://localhost:8080/#) in copy(self, deep, data)
   1300         pandas.DataFrame.copy
   1301         """
-> 1302         return self._copy(deep=deep, data=data)
   1303 
   1304     def _copy(

[/usr/local/lib/python3.10/dist-packages/xarray/core/dataarray.py](https://localhost:8080/#) in _copy(self, deep, data, memo)
   1308         memo: dict[int, Any] | None = None,
   1309     ) -> Self:
-> 1310         variable = self.variable._copy(deep=deep, data=data, memo=memo)
   1311         indexes, index_vars = self.xindexes.copy_indexes(deep=deep)
   1312 

[/usr/local/lib/python3.10/dist-packages/xarray/core/variable.py](https://localhost:8080/#) in _copy(self, deep, data, memo)
    955             ndata = as_compatible_data(data)
    956             if self.shape != ndata.shape:  # type: ignore[attr-defined]
--> 957                 raise ValueError(
    958                     f"Data shape {ndata.shape} must match shape of object {self.shape}"  # type: ignore[attr-defined]
    959                 )

ValueError: Data shape (1,) must match shape of object (0,)

**Comment by raspstephan** [comment]
Thank you for noticing. Yes, the 64x32 files in the bucket are wrong (they should be without poles). I just started the upload for the correct files but it might take a few hours. I will then also delete the 64x32 files with poles. Please let me know if it works now.

**Comment by ShileiCao** [comment]
Thanks for fixing that. 
But there is a small error in the beginning when import the apache_beam. It seems to be due to a problem with the pandas version.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-2-9f5e1ff5be4f>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import apache_beam   # Needs to be imported separately to avoid TypingError
      2 import weatherbench2
      3 import xarray as xr

11 frames
[/usr/local/lib/python3.10/dist-packages/pandas/core/arrays/boolean.py](https://localhost:8080/#) in coerce_to_array(values, mask, copy)
    198         integer_like = ("floating", "integer", "mixed-integer-float")
    199         if inferred_dtype not in ("boolean", "empty") + integer_like:
--> 200             raise TypeError("Need to pass bool-like values")
    201 
    202         # mypy does not narrow the type of mask_values to npt.NDArray[np.bool_]

TypeError: Need to pass bool-like values
