### ISSUE TITLE
aggregating and preparing data from the Climate Data Store

### ISSUE THREAD

**Issue by briansynthetaic** [google-research/weatherbench2#218]
Is there a set of instructions or script for preparing hres or era5 data from Climate Data Store for testing with more recent, 2024 data? I'm hoping to prepare data in a way that is identical to example data, like "source-hres_date-2022-03-29_res-0.25_levels-13_steps-30.nc".

**Comment by raspstephan** [comment]
Unfortunately, the code we used for this is Google-internal. Having said this, we are in the process of updating the data but unfortunately this can take a while.
