### ISSUE TITLE
No permission to access Google Cloud Storage gs://weatherbench2？

### ISSUE THREAD

**Issue by melodicdeath** [google-research/weatherbench2#224]
I got an error running quickstart：
evaluate_in_memory(data_config, eval_configs)   # Takes around 5 minutes

RefreshError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7f76079606d0>)

I try to access:
gcs_client = storage.Client.create_anonymous_client()
gcs_bucket = gcs_client.get_bucket("weatherbench2")

InvalidOperation: Anonymous credentials cannot be refreshed.

**Comment by raspstephan** [comment]
Did you run this?
```
# Run the code below to access cloud data on Colab!
from google.colab import auth
auth.authenticate_user()
```

**Comment by melodicdeath** [comment]
Oh,I'm sorry,it worked.Thank you very much.
