### ISSUE TITLE
v_component_of_wind null values

### ISSUE THREAD

**Issue by leaver2000** [google-research/weatherbench2#50]
If this is not the best place to submit an issue, please let me know.  Is there something I missed in the documentation regarding `null` values?  I've only noticed the issue with the `v_component_of_wind`

```python
assert (
    xr.open_zarr(
        "/mnt/data/era5/1959-2022-6h-128x64_equiangular_with_poles_conservative.zarr",
    )
    .isel({"time": slice(10, 20)})["v_component_of_wind"]
    .isnull()
    .all()
    .compute()
    .item()
)
```

**Comment by shoyer** [comment]
When I try running your example on the original data stored in GCS there is no missing data: `gs://weatherbench2/datasets/era5/1959-2022-6h-128x64_equiangular_with_poles_conservative.zarr`

I think you just have an incomplete copy of the Zarr files. If you're missing some files from a Zarr store, Zarr will return the default value (NaN in this case).

**Comment by leaver2000** [comment]
> When I try running your example on the original data stored in GCS there is no missing data: `gs://weatherbench2/datasets/era5/1959-2022-6h-128x64_equiangular_with_poles_conservative.zarr`
> 
> 
> 
> I think you just have an incomplete copy of the Zarr files. If you're missing some files from a Zarr store, Zarr will return the default value (NaN in this case).

That makes sense, thanks.
