### ISSUE TITLE
ERA5 full 37 levels use (old?) version of ERA5 with wrong u/v wind

### ISSUE THREAD

**Issue by dominique-brunet-eccc** [google-research/weatherbench2#55]
The data downloaded from here gs://weatherbench2/datasets/era5/1959-2022-full_37-1h-0p25deg-chunk-1.zarr-v2 has the wrong u/v wind, probably related to previous issue from Copernicus resolved on January 2019:
https://confluence.ecmwf.int/pages/viewpage.action?pageId=127305868
One should check if the other ERA5 data on weatherbench2 also have the wrong u/v wind (it is unclear how this issue will affect training of AI models, their initialization and verification as everything is using the same wrong data),  but for sure verification against wind observations will do very poorly.

Here is an example of comparison of ERA5-weatherbench2 wind, ERA5-copernicus wind and radiosonde at the same time and location:
![download](https://github.com/google-research/weatherbench2/assets/136009011/912cf392-0282-4a1c-8a2b-7facdf8700aa)
![download](https://github.com/google-research/weatherbench2/assets/136009011/93f2d713-3d5c-4fd7-8d53-e98ac8213599)

Exact code to reproduce example will need the data from each source, but specific example is for ERA5 on 2021-06-01 at 23Z downloaded both from WeatherBench2 and Copernicus Data Store compared against radiosonde with nominal time 2021-06-02 at 00Z (exact launch at 23Z20) and location nearest to 42.751750 latitude and -73.811280 longitude.

**Comment by raspstephan** [comment]
Thanks for flagging this. We will look into it and update the data soon.

**Comment by dominique-brunet-eccc** [comment]
OK, thanks for looking into this. Good to know that the data is correct (albeit using a different longitude convention). It would be nice if .sel would wrap around the coordinates to avoid this type of mistake, but this is a different issue.
