### ISSUE TITLE
Add solar irradiance variable(s)

### ISSUE THREAD

**Issue by williamhobbs** [google-research/weatherbench2#69]
It would be great if one or more surface variables related to solar energy for solar power forecasting, like downward short-wave radiation flux/surface solar radiation downwards or total cloud cover, could be added for evaluation. 

Deterministic and probabilistic forecasts for solar power are going to be increasingly important for power grid operators, and understanding how existing and new forecast models perform in this area would be valuable.

**Comment by raspstephan** [comment]
Great idea. We don't have those variables downloaded at the moment (except for total_cloud_cover for ERA). Can you maybe point out which variables from these (https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels?tab=overview) you'd be interested in specifically?

**Comment by williamhobbs** [comment]
Thanks!

I think `Mean surface downward short-wave radiation flux` would be the most relevant ERA5 variable for solar energy. 

If you were interested in adding wind energy, `100m u-component of wind` and `100m v-component of wind` would be relevant.

**Comment by raspstephan** [comment]
Hi, we have updated our ERA5 dataset which now includes the downward flux but not the 100m winds: gs://weatherbench2/datasets/era5/1959-2023_01_10-full_37-1h-0p25deg-chunk-1.zarr

A related project at Google has a much more comprehensive copy: gs://gcp-public-data-arco-era5/ar/full_37-1h-0p25deg-chunk-1.zarr-v3 

We will merge these versions soon but for now I will close this issue
